CREATE TABLE 'users' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'email' TEXT(254) NOT NULL ,
'password' TEXT(128) NOT NULL 
);

CREATE TABLE 'packages' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'title' TEXT(50) DEFAULT NULL,
'trackingNumber' TEXT NOT NULL ,
'userID' INTEGER NOT NULL  REFERENCES 'users' ('id'),
'last_updated' INTEGER(15) NOT NULL  DEFAULT 0
);

CREATE TABLE 'queue' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'package_id' INTEGER NOT NULL  REFERENCES 'packages' ('id')
);